spring:
  datasource:
    password: ${APP_PASSWORD:folder_app_pwd}
    username: ${APP_USER:folder_app_user}
    url: ${APP_DB_LOCAL_URL:jdbc:postgresql://localhost:5441/folder_app_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: public
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 12MB
      file-size-threshold: 2KB
  flyway:
    locations: classpath:db/migration
    enabled: false
server:
  port: 8092
  servlet:
    context-path: /api/v1
  security:
    jwt:
      secret: 04d0c3110ff96c918f7a405a313c2296d579c5108f36924dbaa7422e4a2aea96814fc32c33a314260014580c130dd52b0bdfb7f2ed618b8cbf543c3f2cb7e59e7d38ed33249a8495961ca3f70168c99c3c9ea77059ad5260ca71caa8ff97d0b1d5fc9c4fd5c92fd3489384340b6916afab0764eec942a39be9817c61bb82f636bf20c64d0e7b22337288d234fdc27e149fb99eac0686fdc5e3275b6e7d2aac6db9a5437655cd01482ee8e5708c42bd146d8936e2246b8d1fbb90c54b3b60937d2c35af2eab9c65a61697a3c02290cd9644622c3be0f3db1e7147200bf9ef28eb482f79584df48aea548ec8f882a47885d0d1b83e9afb275081c4bca966edcc2d
cors:
  allowed-origins:
    dev: "http://localhost:4200"
    prod: "http://localhost:4200"
